name: typelevel-roles
version: 0.1.0.0
github: "githubuser/typelevel-roles"
license: BSD3
author: "Dobromir Nikolov"
maintainer: "dnikolovv@hotmail.com"
copyright: "2022 Dobromir Nikolov"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/typelevel-roles#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - aeson
  - microlens
  - jose
  - wai
  - wai-extra
  - warp
  - servant
  - servant-auth
  - servant-auth-server
  - servant-server
  - mtl
  - rio

default-extensions:
  - ImportQualifiedPost

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  typelevel-roles-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - typelevel-roles

tests:
  typelevel-roles-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - typelevel-roles
